# 住基マッチング処理マッチング条件設定ファイル
# 住基マッチング処理においてマッチング条件にしたい項目を設定する。
# 当ファイルで設定した項目をキーに住基データを検索し、対象者の絞込みを行う。
# マッチング処理は当設定ファイルの上から順に行われ、各項目はAND条件となる。
#
# サンプル:
# - # 検索パターンサンプル1
#   - :alternate_family_name # 氏名カナ（姓）
#   - :alternate_given_name # 氏名カナ（名）
# - # 検索パターンサンプル2
#   - :date_of_birth # 生年月日
#   - :sex # 性別
#   - :home_street # 町名
#
# 上記サンプルの場合、一度目のマッチング処理では検索パターンサンプル1が使用される。
# 一度目のマッチング処理でマッチングを行った結果、対象者が複数存在するまたは対象者無しの場合、
# 二度目のマッチング処理が行われる。二度目のマッチング処理には検索パターンサンプル2が使用される。
# 二度目のマッチング処理でマッチングを行った結果、対象者が複数存在するまたは対象者無しの場合、
# 次の検索パターンを実行する。以降、この処理を繰り返し、対象者が1名に絞られた時点で処理を終了する。
# 最後まで対象者が1名に絞られなかった場合は、対象者無しとする。
#
# マッチング条件に使用できる項目は以下。
# :family_name 氏名（姓）の完全一致
# :given_name 氏名（名）の完全一致
# :alternate_family_name 氏名カナ（姓）の完全一致
# :alternate_given_name 氏名カナ（名）の完全一致
# :date_of_birth 生年月日の完全一致
# :sex 性別の完全一致
# :home_state 都道府県の部分一致
# :home_city 市区町村の部分一致
# :home_street 町名の部分一致
#
- # 検索パターン1
  - :alternate_family_name # 氏名カナ（姓）
  - :alternate_given_name # 氏名カナ（名）
- # 検索パターン2
  - :date_of_birth # 生年月日
  - :sex # 性別
  - :home_street # 町名
- # 検索パターン3
  - :alternate_family_name # 氏名カナ（姓）
  - :alternate_given_name # 氏名カナ（名）
  - :date_of_birth # 生年月日
- # 検索パターン4
  - :alternate_family_name # 氏名カナ（姓）
  - :alternate_given_name # 氏名カナ（名）
  - :home_street # 町名